from __future__ import annotations

import json
import os
from collections import Counter
from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console
from rich.markup import escape
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.table import Table
from typer.completion import get_completion_script

from .config import configured_path, latest_export_json, load_user_config, save_user_config
from .importer import (
    apply_topic_map,
    attach_pdf,
    clean_staging,
    cleanup_run_selected_only,
    concept_index,
    confirm_no_publication_keywords,
    doctor_vault,
    enrich_citations,
    enrich_vault,
    export_bibtex,
    find_staged_run_matches,
    import_bibtex,
    import_doi,
    import_pdf_dropins,
    import_scholar_labs_run,
    initialize_vault,
    latest_run_id,
    list_unmatched,
    notes_missing,
    pdf_doctor,
    proposal_audit,
    proposal_sprint_scaffold,
    rebuild_vault,
    rename_run,
    reset_vault,
    resume_run,
    set_manual_abstract,
    set_manual_keywords,
    set_manual_metadata,
    topic_map_report,
    undo_run,
)
from .models import (
    ImportCanceled,
    MatchReviewAbort,
    MatchReviewRequest,
    ScholarLabsExport,
    SourceCard,
)
from .sources import VaultPaths, infer_run_title, load_run_records, load_source_cards

app = typer.Typer(help="Local-first research source wiki and vault manager.")
proposal_sprint_app = typer.Typer(help="Proposal sprint workspace helpers.")
app.add_typer(proposal_sprint_app, name="proposal-sprint")
console = Console()


def _fish_completion_path() -> Path:
    config_home = os.environ.get("XDG_CONFIG_HOME")
    base = Path(config_home).expanduser() if config_home else Path.home() / ".config"
    return base / "fish" / "completions" / "scholar-vault.fish"


def _fish_completion_script() -> str:
    script = get_completion_script(
        prog_name="scholar-vault",
        complete_var="_SCHOLAR_VAULT_COMPLETE",
        shell="fish",
    )
    return "\n".join(
        [
            "# Generated by `scholar-vault install-fish-completion`.",
            "# This file delegates command, option, and value completion back to Typer.",
            script,
            "",
        ]
    )


def _completion_vault_path(ctx) -> Path | None:
    value = None
    if ctx is not None:
        value = ctx.params.get("vault")
    return value or configured_path("vault")


def _complete_run_ids(ctx, args: list[str], incomplete: str) -> list[str]:
    _ = args
    vault = _completion_vault_path(ctx)
    if vault is None:
        return []
    try:
        paths = VaultPaths.from_root(Path(vault).expanduser().resolve())
        run_ids = [run.slug for run in load_run_records(paths)]
    except Exception:
        return []
    needle = incomplete.casefold()
    return [run_id for run_id in run_ids if run_id.casefold().startswith(needle)]


def _complete_citekeys(ctx, args: list[str], incomplete: str) -> list[str]:
    _ = args
    vault = _completion_vault_path(ctx)
    if vault is None:
        return []
    try:
        paths = VaultPaths.from_root(Path(vault).expanduser().resolve())
        citekeys = [card.citekey for card in load_source_cards(paths) if card.citekey]
    except Exception:
        return []
    needle = incomplete.casefold()
    return [citekey for citekey in citekeys if citekey and citekey.casefold().startswith(needle)]


def _complete_only_modes(incomplete: str) -> list[str]:
    values = ["all", "missing-doi", "missing-bibtex", "missing-abstract", "missing-keywords"]
    return [value for value in values if value.startswith(incomplete)]


def _complete_folder_modes(incomplete: str) -> list[str]:
    values = ["shared", "separate"]
    return [value for value in values if value.startswith(incomplete)]

VaultArg = Annotated[
    Path | None,
    typer.Option("--vault", exists=True, file_okay=False, dir_okay=True, resolve_path=True),
]
NewVaultArg = Annotated[
    Path,
    typer.Option(..., exists=False, file_okay=False, dir_okay=True, resolve_path=True),
]
ExportArg = Annotated[
    Path,
    typer.Option(..., exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
OptionalExportArg = Annotated[
    Path | None,
    typer.Option("--export", exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
PdfArg = Annotated[
    Path,
    typer.Option(..., exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
OptionalPdfArg = Annotated[
    Path | None,
    typer.Option("--pdf", exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
StagingArg = Annotated[
    Path | None,
    typer.Option("--staging", exists=True, file_okay=False, dir_okay=True, resolve_path=True),
]
ConfigPathArg = Annotated[
    Path | None,
    typer.Option(exists=True, file_okay=False, dir_okay=True, resolve_path=True),
]
FishCompletionPathArg = Annotated[
    Path | None,
    typer.Option(
        "--path",
        exists=False,
        file_okay=True,
        dir_okay=False,
        resolve_path=True,
        help=(
            "Completion file to write. Defaults to "
            "~/.config/fish/completions/scholar-vault.fish."
        ),
    ),
]
FolderModeArg = Annotated[
    str | None,
    typer.Option(
        "--folder-mode",
        autocompletion=_complete_folder_modes,
        help=(
            "Scholar Labs download layout: 'shared' uses the staging folder for PDFs and "
            "JSON exports; 'separate' uses --exports."
        ),
    ),
]
RunIdArg = Annotated[
    str,
    typer.Option(
        ...,
        autocompletion=_complete_run_ids,
        help="Run id, for example 2026-04-22_example-prompt.",
    ),
]
OptionalRunIdArg = Annotated[
    str | None,
    typer.Option(
        "--run",
        autocompletion=_complete_run_ids,
        help="Run id. If omitted for rerun, the most recent run is used.",
    ),
]
TitleArg = Annotated[
    str | None,
    typer.Option("--title", help="Short run title used for Obsidian run-note names."),
]
MatchTitleArg = Annotated[
    str | None,
    typer.Option(
        "--title",
        help="Title text to search for across previous Scholar Labs run results.",
    ),
]
RequiredTitleArg = Annotated[
    str,
    typer.Option("--title", help="Short run title used for Obsidian run-note names."),
]
DryRunArg = Annotated[
    bool,
    typer.Option("--dry-run", help="Plan matches without copying PDFs or creating cards."),
]
CommitArg = Annotated[
    bool,
    typer.Option(
        "--commit",
        help="Commit high-confidence matches without interactive confirmation.",
    ),
]
IncludeWithoutPdfArg = Annotated[
    bool,
    typer.Option(
        "--include-without-pdf",
        help="Create candidate paper cards for results that do not have matched PDFs.",
    ),
]
AutoEnrichArg = Annotated[
    bool,
    typer.Option(
        "--enrich/--no-enrich",
        help=(
            "Run citation, abstract, and keyword enrichment after accepted "
            "Scholar Labs matches."
        ),
    ),
]
UpgradePdfsArg = Annotated[
    bool,
    typer.Option(
        "--upgrade-pdfs/--keep-existing-pdfs",
        help=(
            "Review staged PDFs as possible replacements for already attached PDFs "
            "when rerunning or re-importing a Scholar Labs export."
        ),
    ),
]
ArchiveExportArg = Annotated[
    bool,
    typer.Option(
        "--archive-export/--keep-export",
        help="Move a successfully used Scholar Labs JSON export into a sibling used/ folder.",
    ),
]
SelectedOnlyArg = Annotated[
    bool,
    typer.Option("--selected-only", help="Keep only paper cards that have attached PDFs."),
]
CitekeyArg = Annotated[str, typer.Option(..., autocompletion=_complete_citekeys)]
OptionalCitekeyArg = Annotated[
    str | None,
    typer.Option("--citekey", autocompletion=_complete_citekeys),
]
AbstractTextArg = Annotated[
    str | None,
    typer.Option("--text", help="Manual abstract text. Use --file for longer abstracts."),
]
AbstractFileArg = Annotated[
    Path | None,
    typer.Option("--file", exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
SourceUrlArg = Annotated[
    str | None,
    typer.Option("--source-url", help="URL where the manual abstract was copied from."),
]
AbstractLockArg = Annotated[
    bool,
    typer.Option(
        "--lock/--no-lock",
        help="Protect the manual abstract from future automatic abstract enrichment.",
    ),
]
KeywordTextArg = Annotated[
    str | None,
    typer.Option("--text", help="Manual keywords. Commas, semicolons, or lines are accepted."),
]
KeywordFileArg = Annotated[
    Path | None,
    typer.Option("--file", exists=True, file_okay=True, dir_okay=False, resolve_path=True),
]
KeywordReplaceArg = Annotated[
    bool,
    typer.Option("--replace/--merge", help="Replace existing keywords instead of merging."),
]
KeywordNoneArg = Annotated[
    bool,
    typer.Option(
        "--none",
        help="Confirm the source has no publication keywords or index terms.",
    ),
]
MetadataDoiArg = Annotated[
    str | None,
    typer.Option("--doi", help="Manual DOI, for example 10.xxxx/example."),
]
MetadataAuthorsArg = Annotated[
    str | None,
    typer.Option("--authors", help="Manual authors. Use semicolons or new lines between names."),
]
MetadataYearArg = Annotated[
    str | None,
    typer.Option("--year", help="Manual publication year."),
]
MetadataVenueArg = Annotated[
    str | None,
    typer.Option("--venue", help="Manual publication venue."),
]
MetadataUrlArg = Annotated[
    str | None,
    typer.Option("--url", help="Manual primary URL."),
]
MetadataLockArg = Annotated[
    bool,
    typer.Option(
        "--lock/--no-lock",
        help="Set metadata_lock after applying manual citation metadata.",
    ),
]
JsonOutputArg = Annotated[
    bool,
    typer.Option("--json", help="Print machine-readable JSON."),
]
HeadingArg = Annotated[
    str,
    typer.Option(
        "--heading",
        help="Markdown subheading to require under the paper card's Notes section.",
    ),
]
TopicMappingArg = Annotated[
    Path | None,
    typer.Option(
        "--mapping",
        exists=True,
        file_okay=True,
        dir_okay=False,
        resolve_path=True,
        help="YAML mapping of old topic labels to new labels, lists, or null to remove.",
    ),
]
ApplyArg = Annotated[
    bool,
    typer.Option("--apply", help="Apply the planned changes. Default is dry-run."),
]
ProposalPathArg = Annotated[
    Path,
    typer.Argument(help="Proposal folder or Markdown file to audit, relative to the vault."),
]
ProposalSlugArg = Annotated[
    str,
    typer.Argument(help="Proposal workspace slug, for example pepr-mobidec."),
]
ProposalTitleArg = Annotated[
    str | None,
    typer.Option("--title", help="Human-readable proposal title."),
]
OnlyArg = Annotated[
    str,
    typer.Option(
        "--only",
        autocompletion=_complete_only_modes,
        help=(
            "Limit enrichment: all, missing-doi, missing-bibtex, "
            "missing-abstract, or missing-keywords."
        ),
    ),
]
RefreshArg = Annotated[
    bool,
    typer.Option("--refresh", help="Reprocess generated or verified citation metadata."),
]
AbstractsArg = Annotated[
    bool,
    typer.Option("--abstracts", help="Enrich abstracts instead of the default citation metadata."),
]
RefreshAbstractsArg = Annotated[
    bool,
    typer.Option("--refresh-abstracts", help="Reprocess resolved or verified abstracts."),
]
RetryFailedArg = Annotated[
    bool,
    typer.Option("--retry-failed", help="Retry unresolved records that hit the retry limit."),
]
ForceArg = Annotated[
    bool,
    typer.Option("--force", help="Process locked metadata records."),
]
UiArg = Annotated[
    bool,
    typer.Option(
        "--ui/--no-ui",
        help="Use the desktop UI when available.",
    ),
]
YesArg = Annotated[
    bool,
    typer.Option("--yes", help="Reset without confirmation."),
]


def _confirm(prompt: str) -> bool:
    return typer.confirm(prompt, default=False)


def _load_export_for_title(export_path: Path) -> ScholarLabsExport:
    return ScholarLabsExport.model_validate_json(export_path.read_text(encoding="utf-8"))


def _prompt_run_title_cli(default_title: str, prompt: str) -> str:
    console.print("Scholar Labs export does not include a run title.")
    console.print("Prompt:")
    console.print(prompt.strip() or "(empty)", soft_wrap=True)
    selected = typer.prompt("Run title", default=default_title)
    return selected.strip() or default_title


def _prompt_run_title_gui(default_title: str, prompt: str, export_path: Path) -> str | None:
    try:
        from .gui import GuiUnavailable, prompt_run_title
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Title UI unavailable ({exc}). Falling back to terminal prompt.")
        return _prompt_run_title_cli(default_title, prompt)
    try:
        return prompt_run_title(default_title, prompt, str(export_path))
    except GuiUnavailable as exc:
        console.print(f"Title UI unavailable ({exc}). Falling back to terminal prompt.")
        return _prompt_run_title_cli(default_title, prompt)


def _resolve_import_title(title: str | None, export_path: Path, *, ui: bool) -> str | None:
    if title and title.strip():
        return title.strip()
    export = _load_export_for_title(export_path)
    if export.title and export.title.strip():
        return export.title.strip()
    default_title = infer_run_title(export.prompt)
    selected = (
        _prompt_run_title_gui(default_title, export.prompt, export_path)
        if ui
        else _prompt_run_title_cli(default_title, export.prompt)
    )
    if selected is None:
        console.print("Import canceled.")
        raise typer.Exit(code=0)
    return selected.strip() or default_title


def _match_review_prompt(request: MatchReviewRequest) -> str:
    return (
        f"Accept match {request.pdf_filename} -> {request.result_title} "
        f"(score={request.score}, reason={request.match_reason})?"
    )


def _terminal_match_review(request: MatchReviewRequest) -> bool:
    console.print()
    console.print(f"[bold]Scholar Labs title:[/bold] {request.result_title}")
    console.print(
        f"[bold]PDF:[/bold] {request.pdf_filename}  "
        f"[bold]score:[/bold] {request.score}  "
        f"[bold]reason:[/bold] {request.match_reason}"
    )
    if request.inferred_title:
        console.print(f"[bold]Inferred PDF title:[/bold] {request.inferred_title}")
    if request.inferred_doi or request.inferred_year:
        console.print(
            f"[bold]PDF metadata:[/bold] DOI={request.inferred_doi or '-'}  "
            f"year={request.inferred_year or '-'}"
        )
    return typer.confirm(_match_review_prompt(request), default=False)


def _match_reviewer(ui: bool):
    if not ui:
        return _terminal_match_review
    try:
        from .gui import GuiUnavailable, make_match_reviewer
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Review UI unavailable ({exc}). Falling back to terminal prompts.")
        return _terminal_match_review
    try:
        return make_match_reviewer()
    except GuiUnavailable as exc:
        console.print(f"Review UI unavailable ({exc}). Falling back to terminal prompts.")
        return _terminal_match_review


def _confirm_callback(ui: bool):
    if not ui:
        return _confirm
    try:
        from .gui import GuiUnavailable, make_confirmer
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Confirmation UI unavailable ({exc}). Falling back to terminal prompts.")
        return _confirm
    try:
        return make_confirmer("Scholar Vault Import")
    except GuiUnavailable as exc:
        console.print(f"Confirmation UI unavailable ({exc}). Falling back to terminal prompts.")
        return _confirm


def _card_followup_kinds(card: SourceCard) -> list[str]:
    issue_states = {"incomplete", "ambiguous", "unresolved"}
    kinds: list[str] = []
    if card.enrichment_refresh:
        kinds.append("refresh")
    if card.enrichment_status in issue_states or card.enrichment_missing:
        kinds.append("metadata")
    if card.citation_status in issue_states:
        kinds.append("citation")
    if card.abstract_status in issue_states:
        kinds.append("abstract")
    if (
        card.pdf
        and not card.keywords
        and card.publication_keywords_status != "absent"
    ):
        kinds.append("keywords")
    if card.doi_status in {"ambiguous", "unresolved"}:
        kinds.append("doi")
    return kinds


def _keyword_followup_count(vault: Path, *, citekey: str | None = None) -> int:
    paths = VaultPaths.from_root(vault)
    cards = load_source_cards(paths)
    count = 0
    for card in cards:
        if citekey and citekey not in {card.citekey, card.slug}:
            continue
        if card.keywords or card.publication_keywords_status == "absent":
            continue
        count += 1
    return count


def _print_keyword_followup_hint(vault: Path, *, citekey: str | None = None) -> None:
    count = _keyword_followup_count(vault, citekey=citekey)
    if not count:
        return
    noun = "paper card" if count == 1 else "paper cards"
    citekey_part = f" --citekey {citekey}" if citekey else ""
    console.print(
        f"Publication keyword follow-up: {count} {noun} still missing keywords. "
        f"Run `scholar-vault enrich --only missing-keywords{citekey_part} --ui` "
        "to review them."
    )


def _followup_issue_label(summary: dict[str, Any] | None) -> str:
    if not summary or not summary.get("count"):
        return "none"
    count = int(summary["count"])
    kind_counts = summary.get("kinds", {})
    if not isinstance(kind_counts, dict) or not kind_counts:
        return f"{count} follow-up"
    order = ["abstract", "keywords", "citation", "metadata", "doi", "refresh"]
    parts = []
    for kind in order:
        kind_count = int(kind_counts.get(kind, 0))
        if not kind_count:
            continue
        parts.append(f"{kind_count} {kind}" if kind_count > 1 else kind)
    suffix = ", ".join(parts)
    label = "follow-up" if count == 1 else "follow-ups"
    return f"{count} {label}: {suffix}"


def _run_followup_issue_summaries(paths, runs) -> dict[str, dict[str, Any]]:
    cards = {f"papers/{card.slug}.md": card for card in load_source_cards(paths)}
    summaries: dict[str, dict[str, Any]] = {}
    for run in runs:
        seen: set[str] = set()
        issue_count = 0
        kind_counts: Counter[str] = Counter()
        for result in run.results:
            if result.status != "selected" or not result.paper_card:
                continue
            if result.paper_card in seen:
                continue
            seen.add(result.paper_card)
            card = cards.get(result.paper_card)
            if card is None:
                continue
            kinds = _card_followup_kinds(card)
            if not kinds:
                continue
            issue_count += 1
            kind_counts.update(set(kinds))
        if issue_count:
            summaries[run.slug] = {
                "count": issue_count,
                "kinds": dict(kind_counts),
            }
    return summaries


def _select_rerun_run_id(vault: Path, run: str | None, *, ui: bool) -> str:
    if run:
        return run
    if not ui:
        return latest_run_id(vault)

    paths = VaultPaths.from_root(vault)
    runs = load_run_records(paths)
    if not runs:
        raise typer.BadParameter(f"No runs found in vault: {paths.vault}")
    try:
        from .gui import GuiUnavailable, choose_rerun
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Rerun UI unavailable ({exc}). Falling back to latest run.")
        return latest_run_id(vault)
    try:
        selected = choose_rerun(
            runs,
            str(paths.vault),
            issue_summaries=_run_followup_issue_summaries(paths, runs),
        )
    except GuiUnavailable as exc:
        console.print(f"Rerun UI unavailable ({exc}). Falling back to latest run.")
        return latest_run_id(vault)
    if selected is None:
        console.print("Rerun canceled.")
        raise typer.Exit(code=0)
    return selected


def _choose_staging_match_run_id(
    vault: Path,
    staging: Path,
    *,
    title: str | None,
    pdf: Path | None,
    min_score: int,
    limit: int,
    unselected_only: bool,
    run_callback=None,
) -> str | None:
    try:
        from .gui import GuiUnavailable, choose_staging_match
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Staging match UI unavailable ({exc}). Falling back to terminal output.")
        return None

    def search_callback(
        query_title: str | None,
        query_pdf: str | None,
        query_min_score: int,
        query_limit: int,
        query_unselected_only: bool,
        progress,
    ) -> dict[str, Any]:
        return find_staged_run_matches(
            vault,
            staging,
            title=query_title,
            pdf_path=Path(query_pdf).expanduser().resolve() if query_pdf else None,
            min_score=query_min_score,
            limit=query_limit,
            unselected_only=query_unselected_only,
            progress=progress,
        )

    try:
        return choose_staging_match(
            str(vault),
            str(staging),
            search_callback,
            title=title,
            pdf=str(pdf) if pdf else None,
            min_score=min_score,
            limit=limit,
            unselected_only=unselected_only,
            run_callback=run_callback,
        )
    except GuiUnavailable as exc:
        console.print(f"Staging match UI unavailable ({exc}). Falling back to terminal output.")
        return None


def _rerun_selected_match(vault: Path, run_id: str) -> None:
    progress_ui = _make_gui_progress(True, "Scholar Vault Import")
    if progress_ui is not None:
        progress_ui(f"Starting reviewed rerun {run_id}", None, None)
        progress_ui("Preparing match-review window", None, None)
    review_match = _match_reviewer(True)
    if progress_ui is not None:
        progress_ui("Preparing confirmation window", None, None)
    confirm = _confirm_callback(True)
    if progress_ui is not None:
        progress_ui("Loading run manifest and staged PDFs", None, None)
    summary = _with_progress(
        f"Rerunning {run_id}",
        lambda report: resume_run(
            vault,
            run_id,
            dry_run=False,
            commit=False,
            auto_enrich=True,
            upgrade_pdfs=True,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=True,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=True, progress_ui=progress_ui)


def _configure_ui(config: dict[str, Any]) -> dict[str, Any] | None:
    try:
        from .gui import GuiUnavailable, edit_configuration
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Configuration UI unavailable ({exc}). Falling back to terminal output.")
        return None
    try:
        return edit_configuration(config)
    except GuiUnavailable as exc:
        console.print(f"Configuration UI unavailable ({exc}). Falling back to terminal output.")
        return None


def _apply_config_options(
    config: dict[str, Any],
    *,
    vault: Path | None,
    staging: Path | None,
    exports: Path | None,
    code: Path | None,
    folder_mode: str | None,
) -> bool:
    changed = False
    if vault is not None:
        config["vault"] = str(vault.expanduser().resolve())
        changed = True
    if staging is not None:
        config["staging"] = str(staging.expanduser().resolve())
        changed = True
    if code is not None:
        config["code"] = str(code.expanduser().resolve())
        changed = True

    normalized_mode = folder_mode.casefold() if folder_mode else None
    if normalized_mode not in (None, "shared", "separate"):
        raise typer.BadParameter("--folder-mode must be 'shared' or 'separate'.")
    if exports is not None and normalized_mode == "shared":
        raise typer.BadParameter("--exports cannot be used with --folder-mode shared.")
    if exports is not None:
        config["exports"] = str(exports.expanduser().resolve())
        changed = True
    if normalized_mode == "shared":
        if "exports" in config:
            config.pop("exports", None)
            changed = True
    if normalized_mode == "separate":
        if not config.get("exports"):
            raise typer.BadParameter("--folder-mode separate requires --exports.")
        changed = True
    return changed


def _print_config(config: dict[str, Any]) -> None:
    if not config:
        console.print("No scholar-vault defaults configured.")
        return

    console.print("Configured scholar-vault defaults:")
    for key in ("code", "vault", "staging", "exports"):
        value = config.get(key)
        if value:
            console.print(f"- {key}: {value}")
    if config.get("staging") and not config.get("exports"):
        console.print("- folder_mode: shared (staging folder also contains JSON exports)")
    elif config.get("exports"):
        console.print("- folder_mode: separate (staging PDFs and JSON exports are separate)")


def _shorten(value: object, limit: int = 76) -> str:
    text = "" if value is None else str(value)
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _short_run_title(run) -> str:
    title = (run.title or "").strip()
    if title:
        return title
    prompt = " ".join((run.prompt or "").split())
    return _shorten(prompt, 80)


def _short_run_timestamp(run) -> str:
    value = run.exported_at or run.date
    if "T" in value:
        return value[:16].replace("T", " ")
    return value


def _run_table_counts(run) -> tuple[int, int]:
    total = run.result_count or len(run.results)
    selected = sum(1 for result in run.results if result.status == "selected")
    return total, selected


def _print_runs_table(vault: Path, *, limit: int | None = None) -> None:
    paths = VaultPaths.from_root(vault)
    runs = sorted(
        load_run_records(paths),
        key=lambda run: (run.exported_at or run.date, run.slug),
        reverse=True,
    )
    if limit is not None and limit > 0:
        runs = runs[:limit]
    if not runs:
        console.print(f"No runs found in {paths.vault}.")
        return

    issue_summaries = _run_followup_issue_summaries(paths, runs)
    console.print("Scholar Vault Runs")
    console.print(f"Vault: {paths.vault}")
    for run in runs:
        total, selected = _run_table_counts(run)
        console.print(f"\n[cyan]{run.slug}[/cyan]")
        console.print(f"  title: {_short_run_title(run)}")
        console.print(f"  exported: {_short_run_timestamp(run)}")
        console.print(f"  results: {total}  selected: {selected}")
        console.print(f"  follow_up: {_followup_issue_label(issue_summaries.get(run.slug))}")


def _print_staged_match_table(summary: dict[str, Any]) -> None:
    rows = list(summary.get("matches") or [])
    scanned = int(summary.get("staged_pdfs_scanned") or 0)
    cache_hits = int(summary.get("staged_pdf_cache_hits") or 0)
    console.print(
        f"Checked {summary.get('runs', 0)} previous runs; "
        f"{scanned} PDF scan(s)"
        f"{f' ({cache_hits} cached)' if cache_hits else ''}; "
        f"{len(rows)} candidate match(es) shown."
    )
    if not rows:
        console.print("No previous run result matched above the selected threshold.")
        return

    table = Table(title="Staging PDF Candidates Across Previous Runs", show_lines=False)
    table.add_column("Score", justify="right", no_wrap=True)
    table.add_column("PDF / Query", no_wrap=False)
    table.add_column("Run", no_wrap=False)
    table.add_column("Rank", justify="right", no_wrap=True)
    table.add_column("State", no_wrap=True)
    table.add_column("Scholar Labs Title", no_wrap=False)
    table.add_column("Next", no_wrap=False)
    for row in rows:
        pdf_label = row.get("pdf_filename") or row.get("query_title") or "(title query)"
        if row.get("pdf_title") and row.get("pdf_title") != pdf_label:
            pdf_label = f"{pdf_label}\n{row['pdf_title']}"
        state = f"{row.get('status')}/{row.get('pdf_status')}"
        if row.get("attached"):
            state += " attached"
        run_id = str(row.get("run_id") or "")
        table.add_row(
            str(row.get("score") or 0),
            escape(_shorten(pdf_label, 58)),
            escape(_shorten(f"{row.get('run_title')}\n{run_id}", 54)),
            str(row.get("rank") or ""),
            escape(state),
            escape(_shorten(row.get("result_title"), 70)),
            escape(f"scholar-vault rerun --run {run_id} --ui"),
        )
    console.print(table)


def _detail_rows(summary: dict[str, Any]) -> list[dict[str, Any]]:
    rows = summary.get("details", [])
    return [row for row in rows if isinstance(row, dict)]


def _print_enrichment_details(summary: dict[str, Any]) -> None:
    rows = _detail_rows(summary)
    if not rows:
        return
    order = [
        "generated",
        "resolved",
        "verified",
        "incomplete",
        "ambiguous",
        "unresolved",
        "skipped",
    ]
    for category in order:
        category_rows = [row for row in rows if row.get("category") == category]
        if not category_rows:
            continue
        table = Table(title=f"{category.title()} ({len(category_rows)})", show_lines=False)
        table.add_column("Type", no_wrap=True)
        table.add_column("Citekey", no_wrap=True)
        table.add_column("Title")
        table.add_column("DOI / Source")
        table.add_column("Missing")
        table.add_column("Message")
        for row in category_rows:
            doi_source = " / ".join(
                part
                for part in [
                    str(row.get("doi") or ""),
                    str(row.get("source") or ""),
                ]
                if part
            )
            missing = ", ".join(row.get("missing_fields") or [])
            table.add_row(
                str(row.get("kind") or ""),
                str(row.get("citekey") or ""),
                _shorten(row.get("title")),
                _shorten(doi_source, 48),
                missing or "-",
                _shorten(row.get("message"), 70),
            )
        console.print(table)


def _print_enrich_pass_summary(label: str, counts: dict[str, Any]) -> None:
    processed = int(counts.get("processed") or 0)
    changed = int(counts.get("changed") or 0)
    skipped = int(counts.get("skipped") or 0)
    ambiguous = int(counts.get("ambiguous") or 0)
    unresolved = int(counts.get("unresolved") or 0)
    console.print(
        f"{label}: processed={processed}, changed={changed}, skipped={skipped}, "
        f"ambiguous={ambiguous}, unresolved={unresolved}."
    )


def _print_enrich_summary(summary: dict[str, Any]) -> None:
    console.print(
        f"Enriched vault: processed={summary['processed']}, changed={summary['changed']}, "
        f"skipped={summary['skipped']}."
    )
    _print_enrich_pass_summary("Citations", summary.get("citation_enrichment") or {})
    _print_enrich_pass_summary("Abstracts", summary.get("abstract_enrichment") or {})
    _print_enrich_pass_summary("Keywords", summary.get("keyword_enrichment") or {})


def _optional_staging_path(staging: Path | None) -> Path | None:
    if staging is not None:
        return _resolve_staging(staging)
    configured = configured_path("staging")
    return configured.expanduser().resolve() if configured else None


def _print_json(data: dict[str, Any]) -> None:
    typer.echo(json.dumps(data, ensure_ascii=False, indent=2))


def _print_issue_counts(title: str, counts: dict[str, Any]) -> None:
    table = Table(title=title, show_lines=False)
    table.add_column("Issue")
    table.add_column("Count", justify="right")
    for key, value in counts.items():
        table.add_row(str(key).replace("_", " "), str(value))
    console.print(table)


def _print_doctor_summary(summary: dict[str, Any]) -> None:
    counts = summary.get("counts") or {}
    console.print(f"Vault: {summary.get('vault')}")
    console.print(
        "Cards={paper_cards}, PDFs={pdf_files}, attached={attached_pdf_cards}, "
        "missing-card-pdfs={missing_pdf_cards}, runs={runs}, topics={topic_pages}".format(
            **counts
        )
    )
    console.print(
        (
            "Candidate results without cards={candidate_results_without_cards}; "
            "historical unmatched manifest entries={historical_unmatched_entries}."
        ).format(**counts)
    )
    if counts.get("active_staging_pdfs") is not None:
        console.print(
            (
                "Active staging PDFs={active_staging_pdfs}; "
                "duplicates already in vault={active_staging_duplicates}; "
                "actionable staging PDFs={active_staging_actionable_pdfs}."
            ).format(**counts)
        )
    _print_issue_counts("Issue Counts", summary.get("issue_counts") or {})
    diagnostic_counts = summary.get("diagnostic_counts") or {}
    if diagnostic_counts:
        _print_issue_counts("Diagnostic Counts", diagnostic_counts)

    status_table = Table(title="Status Counts", show_lines=False)
    status_table.add_column("Field")
    status_table.add_column("Counts")
    for field, values in (summary.get("status_counts") or {}).items():
        rendered = ", ".join(f"{key}={value}" for key, value in values.items())
        status_table.add_row(str(field), rendered or "-")
    console.print(status_table)

    topic_noisy = (summary.get("topics") or {}).get("noisy") or []
    if topic_noisy:
        table = Table(title="Noisy Topics", show_lines=False)
        table.add_column("Topic")
        table.add_column("Count", justify="right")
        for row in topic_noisy[:20]:
            table.add_row(str(row["topic"]), str(row["count"]))
        console.print(table)

    pdfs = summary.get("pdfs") or {}
    console.print(
        "PDF doctor: orphan={orphan}, duplicate-hash-groups={dupes}, "
        "duplicate-style-names={styled}, repeated-unmatched={repeated}.".format(
            orphan=len(pdfs.get("orphan_pdfs") or []),
            dupes=len(pdfs.get("duplicate_hashes") or []),
            styled=len(pdfs.get("duplicate_style_filenames") or []),
            repeated=len(pdfs.get("repeated_unmatched_files") or []),
        )
    )


def _print_pdf_doctor_summary(summary: dict[str, Any]) -> None:
    console.print(f"Vault: {summary.get('vault')}")
    console.print(
        f"PDF files={summary.get('pdf_files')}; cards={summary.get('cards')}; "
        f"cards with pdf={summary.get('cards_with_pdf')}."
    )
    for key, label in [
        ("missing_card_pdfs", "Cards With Missing PDF Files"),
        ("cards_without_pdf", "Cards Without PDF"),
        ("orphan_pdfs", "Orphan PDFs"),
        ("duplicate_style_filenames", "Duplicate-Style Filenames"),
        ("repeated_unmatched_files", "Repeated Unmatched Staging Files"),
    ]:
        rows = summary.get(key) or []
        if not rows:
            continue
        table = Table(title=f"{label} ({len(rows)})", show_lines=False)
        table.add_column("Item")
        table.add_column("Detail")
        for row in rows[:50]:
            if isinstance(row, dict):
                item = str(row.get("paper") or row.get("filename") or row.get("citekey") or "")
                detail = str(row.get("title") or row.get("count") or row.get("pdf") or "")
            else:
                item = str(row)
                detail = ""
            table.add_row(item, detail)
        console.print(table)
    duplicates = summary.get("duplicate_hashes") or []
    if duplicates:
        table = Table(title=f"Duplicate PDF Hashes ({len(duplicates)})", show_lines=False)
        table.add_column("SHA256")
        table.add_column("Files")
        for row in duplicates[:50]:
            table.add_row(str(row["sha256"])[:16], ", ".join(row["files"]))
        console.print(table)
    staging = summary.get("staging")
    if staging:
        console.print(
            f"Staging: {staging['path']} has {staging['pdf_count']} PDFs; "
            f"{staging['duplicate_count']} duplicate vault copies; "
            f"{staging['actionable_pdf_count']} actionable PDFs."
        )


def _print_topic_report(summary: dict[str, Any]) -> None:
    console.print(f"Vault: {summary.get('vault')}")
    console.print(f"Topic count: {summary.get('topic_count')}")
    table = Table(title="Top Topics", show_lines=False)
    table.add_column("Topic")
    table.add_column("Count", justify="right")
    for row in summary.get("top") or []:
        table.add_row(str(row["topic"]), str(row["count"]))
    console.print(table)
    noisy = summary.get("noisy") or []
    if noisy:
        noise_table = Table(title="Likely Prompt Noise", show_lines=False)
        noise_table.add_column("Topic")
        noise_table.add_column("Count", justify="right")
        for row in noisy:
            noise_table.add_row(str(row["topic"]), str(row["count"]))
        console.print(noise_table)


def _print_topic_map_summary(summary: dict[str, Any]) -> None:
    mode = "Applied" if summary.get("applied") else "Dry-run"
    console.print(f"{mode} topic map: {summary['changed_cards']} card(s) would change.")
    if summary.get("removed_topics"):
        console.print(
            "Removed/replaced: "
            + ", ".join(
                f"{topic}={count}" for topic, count in summary["removed_topics"].items()
            )
        )
    if summary.get("added_topics"):
        console.print(
            "Added: "
            + ", ".join(f"{topic}={count}" for topic, count in summary["added_topics"].items())
        )
    changes = summary.get("changes") or []
    if changes:
        table = Table(title="Changed Cards", show_lines=False)
        table.add_column("Paper")
        table.add_column("Before")
        table.add_column("After")
        for row in changes[:50]:
            table.add_row(
                str(row["paper"]),
                ", ".join(row["before"]),
                ", ".join(row["after"]),
            )
        console.print(table)


def _print_proposal_audit(summary: dict[str, Any]) -> None:
    status = "OK" if summary.get("ok") else "ISSUES"
    console.print(f"Proposal audit: {summary.get('proposal')} [{status}]")
    counts = summary.get("counts") or {}
    console.print(
        "Files={files}, paper refs={paper_refs}, read papers={read_papers}, "
        "outlines={outline_files}, matrices={source_matrix_files}.".format(**counts)
    )
    _print_issue_counts("Proposal Audit Issues", summary.get("issue_counts") or {})
    issues = summary.get("issues") or {}
    for key, rows in issues.items():
        if not rows:
            continue
        table = Table(title=key.replace("_", " ").title(), show_lines=False)
        table.add_column("File")
        table.add_column("Paper/Target")
        table.add_column("Message")
        for row in rows[:50]:
            table.add_row(
                str(row.get("file") or "-"),
                str(row.get("paper") or row.get("target") or "-"),
                str(row.get("message") or ""),
            )
        console.print(table)


def _print_notes_missing(summary: dict[str, Any]) -> None:
    status = "OK" if summary.get("ok") else "MISSING"
    console.print(f"Notes check: heading={summary.get('heading')!r} [{status}]")
    console.print(
        "Eligible cards={eligible_cards}, present={present}, missing={missing}.".format(
            **summary
        )
    )
    rows = summary.get("missing_cards") or []
    if not rows:
        return
    table = Table(title="Cards Missing Notes Heading", show_lines=False)
    table.add_column("Paper")
    table.add_column("Title")
    table.add_column("PDF")
    for row in rows[:80]:
        table.add_row(
            str(row.get("paper") or ""),
            str(row.get("title") or ""),
            str(row.get("pdf") or ""),
        )
    console.print(table)


def _print_concept_index(summary: dict[str, Any]) -> None:
    console.print(
        f"Wrote {summary.get('index')} with {summary.get('concepts')} concept card(s)."
    )
    if summary.get("llm_files_written"):
        console.print(f"Refreshed {summary.get('llm_files_written')} LLM context file(s).")


def _print_proposal_scaffold(summary: dict[str, Any]) -> None:
    console.print(f"Proposal sprint scaffold: {summary.get('proposal')}")
    files = summary.get("files") or {}
    for state in ("created", "updated", "unchanged"):
        values = files.get(state) or []
        if values:
            console.print(f"- {state.title()}: {', '.join(values)}")
    rebuild = summary.get("rebuild") or {}
    if rebuild:
        console.print(
            "- Rebuilt derived outputs: "
            f"{rebuild.get('index_files_written')} indexes, "
            f"{rebuild.get('llm_files_written')} LLM files."
        )


def _show_enrichment_ui(
    summary: dict[str, Any],
    *,
    abstracts: bool,
    title: str | None = None,
    close_label: str | None = None,
) -> bool:
    rows = _problem_rows(_detail_rows(summary))
    if not rows:
        return False
    try:
        from .gui import GuiUnavailable, show_enrichment_results
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Review UI unavailable ({exc}). Showing terminal details instead.")
        return False
    try:
        show_enrichment_results(
            rows,
            abstracts=abstracts,
            title=title,
            close_label=close_label,
        )
    except GuiUnavailable as exc:
        console.print(f"Review UI unavailable ({exc}). Showing terminal details instead.")
        return False
    return True


def _make_gui_progress(enabled: bool, title: str):
    if not enabled:
        return None
    try:
        from .gui import GuiUnavailable, make_progress_reporter
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Progress UI unavailable ({exc}). Showing terminal progress instead.")
        return None
    try:
        return make_progress_reporter(title)
    except GuiUnavailable as exc:
        console.print(f"Progress UI unavailable ({exc}). Showing terminal progress instead.")
        return None


def _close_gui_progress(progress_ui) -> None:
    if progress_ui is not None:
        progress_ui.close()


def _show_import_summary_ui(
    summary: dict[str, Any],
    *,
    ui: bool,
    followup_pending: bool = False,
) -> str | None:
    if not ui:
        return None
    try:
        from .gui import GuiUnavailable, show_import_summary
    except Exception as exc:  # pragma: no cover - defensive optional import path
        console.print(f"Summary UI unavailable ({exc}).")
        return None
    try:
        return show_import_summary(
            summary,
            _import_summary_lines(summary),
            followup_pending=followup_pending,
            leftover_pending=_has_leftover_staging_pdfs(summary),
        )
    except GuiUnavailable as exc:
        console.print(f"Summary UI unavailable ({exc}).")
    return None


def _run_enrichment_rows(summary: dict[str, Any]) -> list[dict[str, Any]]:
    rows = []
    for key in ("enrichment_details", "abstract_details", "keyword_details"):
        value = summary.get(key, [])
        rows.extend(row for row in value if isinstance(row, dict))
    return rows


def _problem_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    problem_categories = {"incomplete", "ambiguous", "unresolved"}
    problem_skip_messages = {
        "retry limit reached",
        "abstract previously failed",
        "metadata_lock",
    }
    return [
        row
        for row in rows
        if row.get("category") in problem_categories
        or (
            row.get("category") == "skipped"
            and str(row.get("message") or "") in problem_skip_messages
        )
    ]


def _show_import_enrichment_followup(summary: dict[str, Any], *, ui: bool) -> None:
    rows = _run_enrichment_rows(summary)
    problems = _problem_rows(rows)
    if ui:
        if problems:
            shown = _show_enrichment_ui(
                {"details": problems},
                abstracts=False,
                title="Scholar Vault Import Follow-Up",
                close_label="Close Follow-Up and Import Log",
            )
            if not shown:
                console.print("Enrichment follow-up issues:")
                _print_enrichment_details({"details": problems})
        elif rows:
            console.print("No enrichment follow-up issues found.")
        return
    if problems:
        console.print("Enrichment follow-up issues:")
        _print_enrichment_details({"details": problems})


def _has_import_followup(summary: dict[str, Any]) -> bool:
    return bool(_problem_rows(_run_enrichment_rows(summary)))


def _has_leftover_staging_pdfs(summary: dict[str, Any]) -> bool:
    remaining = int(summary.get("staging_pdfs_remaining") or summary.get("unmatched") or 0)
    return remaining > 0 and bool(summary.get("staging_folder"))


def _run_staging_match_from_summary(summary: dict[str, Any]) -> None:
    vault_value = summary.get("vault")
    staging_value = summary.get("staging_folder")
    if not vault_value or not staging_value:
        console.print("No staging folder was recorded for this import.")
        return
    vault = Path(str(vault_value)).expanduser().resolve()
    staging = Path(str(staging_value)).expanduser().resolve()
    _choose_staging_match_run_id(
        vault,
        staging,
        title=None,
        pdf=None,
        min_score=60,
        limit=50,
        unselected_only=True,
        run_callback=lambda run_id: _rerun_selected_match(vault, run_id),
    )


def _finish_import_workflow(
    summary: dict[str, Any],
    *,
    ui: bool,
    progress_ui=None,
) -> None:
    try:
        _print_run_summary(summary)
        action = _show_import_summary_ui(
            summary,
            ui=ui,
            followup_pending=_has_import_followup(summary),
        )
        if action == "leftovers":
            _close_gui_progress(progress_ui)
            progress_ui = None
            _run_staging_match_from_summary(summary)
            return
        _show_import_enrichment_followup(summary, ui=ui)
    finally:
        _close_gui_progress(progress_ui)


def _require_configured_path(
    explicit: Path | None,
    key: str,
    *,
    label: str,
    must_be_file: bool = False,
    must_be_dir: bool = True,
) -> Path:
    path = explicit or configured_path(key)
    if path is None:
        raise typer.BadParameter(
            f"No {label} was provided and no default is configured. "
            "Run `scholar-vault configure` to store default paths."
        )
    resolved = path.expanduser().resolve()
    if must_be_file and not resolved.is_file():
        raise typer.BadParameter(f"Configured {label} is not a file: {resolved}")
    if must_be_dir and not resolved.is_dir():
        raise typer.BadParameter(f"Configured {label} is not a directory: {resolved}")
    return resolved


def _resolve_vault(vault: Path | None) -> Path:
    return _require_configured_path(vault, "vault", label="vault path")


def _resolve_staging(staging: Path | None) -> Path:
    return _require_configured_path(staging, "staging", label="staging folder")


def _resolve_latest_export(export: Path | None, *, fallback_dir: Path | None = None) -> Path:
    if export is not None:
        return export.expanduser().resolve()

    exports_dir = configured_path("exports")
    exports_error = ""
    if exports_dir is not None:
        resolved_exports = exports_dir.expanduser().resolve()
        if not resolved_exports.is_dir():
            raise typer.BadParameter(
                f"Configured exports folder is not a directory: {resolved_exports}"
            )
        try:
            return latest_export_json(resolved_exports)
        except FileNotFoundError as exc:
            exports_error = str(exc)

    if fallback_dir is not None:
        try:
            return latest_export_json(fallback_dir)
        except FileNotFoundError as exc:
            fallback_label = f"No JSON export files found in staging folder {fallback_dir}"
            if exports_error:
                raise typer.BadParameter(f"{exports_error}; {fallback_label}") from exc
            raise typer.BadParameter(str(exc)) from exc

    if exports_dir is None:
        raise typer.BadParameter(
            "No export was provided and no exports folder is configured. "
            "Pass --export, configure an exports folder, or configure/use a staging folder "
            "that contains the Scholar Labs JSON export."
        )
    raise typer.BadParameter(exports_error)


def _print_run_summary(summary: dict[str, Any]) -> None:
    for line in _import_summary_lines(summary):
        console.print(line)
    if summary.get("export_archived"):
        console.print(f"Archived used export JSON to {summary['export_archived']}.")


def _import_summary_lines(summary: dict[str, Any]) -> list[str]:
    decisions = summary.get("decision_summary") or {}
    citations = summary.get("citation_enrichment") or {}
    abstracts = summary.get("abstract_enrichment") or {}
    keywords = summary.get("keyword_enrichment") or {}
    selected = int(summary.get("selected") or 0)
    reused = int(decisions.get("prior_selected_reused") or 0)
    linked = int(decisions.get("existing_cards_linked") or 0)
    new_matches = int(decisions.get("new_staged_pdf_matches") or 0)
    review_prompts = int(decisions.get("review_prompts") or 0)
    review_accepted = int(decisions.get("review_accepted") or 0)
    review_rejected = int(decisions.get("review_rejected") or 0)
    unselected = int(summary.get("unselected_results") or 0)
    export_results = int(decisions.get("export_results") or selected + unselected)
    skipped_commit = int(decisions.get("commit_proposals_skipped") or 0)
    not_committed = int(decisions.get("proposed_not_committed") or 0)
    without_candidate = int(decisions.get("results_without_candidate") or 0)
    pdf_upgrades = int(decisions.get("pdf_upgrades") or 0)
    other_runs_synced = int(decisions.get("other_runs_synced") or 0)
    scanned_pdfs = int(decisions.get("staged_pdfs_scanned") or 0)
    scan_cache_hits = int(decisions.get("staged_pdf_cache_hits") or 0)
    scan_cache_part = (
        f"{scan_cache_hits} reused from scan cache; " if scan_cache_hits else ""
    )
    lines = [
        f"Processed run {summary['run']}.",
        (
            f"- Results: {export_results} in export; "
            f"{selected} selected paper cards; {unselected} left unselected."
        ),
        (
            "- Selection source: "
            f"{reused} reused from previous run manifest, "
            f"{linked} linked to existing vault cards, "
            f"{new_matches} newly accepted staged PDFs."
        ),
        (
            "- Match review: "
            f"{review_prompts} prompts shown "
            f"({review_accepted} accepted, {review_rejected} rejected)."
        ),
        (
            "- Staging: "
            f"{scanned_pdfs} PDFs found; "
            f"{scan_cache_part}"
            f"{int(summary.get('unmatched') or 0)} unmatched PDFs remain; "
            f"{int(summary.get('archived') or 0)} matched staging PDFs archived."
        ),
    ]
    if unselected:
        lines.append(
            "- Unselected reasons: "
            f"{without_candidate} had no staged PDF candidate above threshold, "
            f"{review_rejected} rejected in review, "
            f"{skipped_commit} skipped by --commit, "
            f"{not_committed} not committed in dry-run."
        )
    citation_processed = int(citations.get("processed") or 0)
    abstract_processed = int(abstracts.get("processed") or 0)
    keyword_processed = int(keywords.get("processed") or 0)
    if citation_processed or abstract_processed or keyword_processed:
        citation_changed = int(citations.get("changed") or 0)
        abstract_changed = int(abstracts.get("changed") or 0)
        keyword_changed = int(keywords.get("changed") or 0)
        citation_unchanged = max(citation_processed - citation_changed, 0)
        abstract_unchanged = max(abstract_processed - abstract_changed, 0)
        keyword_unchanged = max(keyword_processed - keyword_changed, 0)
        lines.append(
            "- Enrichment: "
            f"citations checked {citation_processed} cards "
            f"({citation_changed} updated, {citation_unchanged} unchanged); "
            f"abstracts checked {abstract_processed} cards "
            f"({abstract_changed} updated, {abstract_unchanged} unchanged); "
            f"keywords checked {keyword_processed} cards "
            f"({keyword_changed} updated, {keyword_unchanged} unchanged)."
        )
    if pdf_upgrades:
        lines.append(
            f"- PDF upgrades: {pdf_upgrades} existing attachment(s) replaced from staging."
        )
    if other_runs_synced:
        lines.append(
            f"- Cross-run links: {other_runs_synced} prior run result(s) now point to "
            "attached paper cards."
        )
    if review_prompts == 0 and selected:
        if reused == selected:
            lines.append(
                "No match-review prompts appeared because every selected result was already "
                "recorded in the existing run manifest."
            )
        elif reused or linked:
            lines.append(
                "Some results did not need review because they were already selected in this "
                "run or already had attached PDFs in the vault."
            )
    if skipped_commit:
        lines.append(
            f"{skipped_commit} proposed matches were skipped because --commit only accepts "
            "high-confidence auto matches."
        )
    if not_committed:
        lines.append(f"{not_committed} proposed matches were not committed during dry-run.")
    return lines


def _with_progress(
    initial_message: str,
    action,
    *,
    interactive: bool = False,
    gui_progress=None,
):
    if interactive:
        console.print(initial_message)

        def plain_report(
            message: str,
            current: int | None = None,
            total: int | None = None,
        ) -> None:
            if gui_progress is not None:
                gui_progress(message, current, total)
            prefix = f"[{current}/{total}] " if current is not None and total else ""
            console.print(f"{prefix}{message}")

        try:
            result = action(plain_report)
            if gui_progress is not None:
                gui_progress("Complete", None, None)
            return result
        except MatchReviewAbort as exc:
            if gui_progress is not None:
                gui_progress.close()
            console.print(str(exc) or "Import aborted.")
            raise typer.Exit(code=130) from exc
        except ImportCanceled as exc:
            if gui_progress is not None:
                gui_progress.close()
            console.print(str(exc) or "Import canceled.")
            raise typer.Exit(code=0) from exc
        except Exception:
            if gui_progress is not None:
                gui_progress.close()
            raise

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task(initial_message, total=None)

        def report(message: str, current: int | None = None, total: int | None = None) -> None:
            if gui_progress is not None:
                gui_progress(message, current, total)
            prefix = f"[{current}/{total}] " if current is not None and total else ""
            progress.update(task, description=f"{prefix}{message}")

        try:
            result = action(report)
        except MatchReviewAbort as exc:
            progress.stop()
            if gui_progress is not None:
                gui_progress.close()
            console.print(str(exc) or "Import aborted.")
            raise typer.Exit(code=130) from exc
        except ImportCanceled as exc:
            progress.stop()
            if gui_progress is not None:
                gui_progress.close()
            console.print(str(exc) or "Import canceled.")
            raise typer.Exit(code=0) from exc
        except Exception:
            if gui_progress is not None:
                gui_progress.close()
            raise
        if gui_progress is not None:
            gui_progress("Complete", None, None)
        progress.update(task, description="Complete")
        return result


def _enrichment_progress_reporter(
    report,
    *,
    abstracts: bool = False,
    keywords: bool = False,
):
    def progress(card: SourceCard, index: int, total: int, status: str) -> None:
        report(
            _enrichment_progress_message(
                card,
                status,
                abstracts=abstracts,
                keywords=keywords,
            ),
            index,
            total,
        )

    return progress


def _enrichment_progress_message(
    card: SourceCard,
    status: str,
    *,
    abstracts: bool = False,
    keywords: bool = False,
) -> str:
    stage = "keywords" if keywords else "abstracts" if abstracts else "citations"
    identifier = card.citekey or card.slug
    title = " ".join((card.title or identifier).split())
    context: list[str] = []
    if keywords:
        keyword_state = "present" if card.keywords else card.publication_keywords_status
        context.append(f"state={keyword_state}")
        context.append(f"count={len(card.keywords)}")
        context.append(f"pdf={'yes' if card.pdf else 'no'}")
    elif abstracts:
        context.append(f"state={card.abstract_status}")
        if card.abstract_source:
            context.append(f"source={card.abstract_source}")
        context.append(f"pdf={'yes' if card.pdf else 'no'}")
        if card.abstract_lock:
            context.append("locked")
    else:
        context.append(f"state={card.citation_status}")
        if card.citation_source:
            context.append(f"source={card.citation_source}")
        if card.enrichment_missing:
            context.append(f"missing={','.join(card.enrichment_missing)}")
        if card.doi:
            context.append(f"doi={card.doi}")
    return f"Enriching {stage} [{status}]: {identifier} // {title} // {'; '.join(context)}"


@app.command("install-fish-completion")
def install_fish_completion_command(path: FishCompletionPathArg = None) -> None:
    target = path or _fish_completion_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_fish_completion_script(), encoding="utf-8")
    console.print(f"Wrote Fish completion to {escape(str(target))}.")
    console.print("Restart Fish or run `exec fish`, then try `scholar-vault enr<Tab>`.")


@app.command("show-fish-completion")
def show_fish_completion_command() -> None:
    typer.echo(_fish_completion_script(), nl=False)


@app.command("configure")
def configure_command(
    vault: ConfigPathArg = None,
    staging: ConfigPathArg = None,
    exports: ConfigPathArg = None,
    code: ConfigPathArg = None,
    folder_mode: FolderModeArg = None,
    ui: UiArg = False,
) -> None:
    config = load_user_config()
    changed = _apply_config_options(
        config,
        vault=vault,
        staging=staging,
        exports=exports,
        code=code,
        folder_mode=folder_mode,
    )

    if ui:
        updated = _configure_ui(config)
        if updated is None:
            if changed:
                config_path = save_user_config(config)
                console.print(f"Wrote scholar-vault defaults to {config_path}.")
            else:
                console.print("Configuration unchanged.")
            _print_config(config)
            return
        config = updated
        changed = True

    if changed:
        config_path = save_user_config(config)
        console.print(f"Wrote scholar-vault defaults to {config_path}.")

    _print_config(config)


@app.command("init")
def init_command(vault: NewVaultArg) -> None:
    paths = initialize_vault(vault)
    console.print(f"Initialized vault at {paths.vault}")


@app.command("runs")
@app.command("list-runs")
def list_runs_command(
    vault: VaultArg = None,
    limit: int = typer.Option(30, "--limit", "-n", help="Maximum runs to show; 0 shows all."),
) -> None:
    _print_runs_table(_resolve_vault(vault), limit=None if limit == 0 else limit)


@app.command("import-run")
def import_run_command(
    export: ExportArg,
    vault: VaultArg = None,
    staging: StagingArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    include_without_pdf: IncludeWithoutPdfArg = False,
    archive_export: ArchiveExportArg = False,
    upgrade_pdfs: UpgradePdfsArg = True,
    title: TitleArg = None,
    ui: UiArg = False,
) -> None:
    resolved_title = _resolve_import_title(title, export, ui=ui)
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    summary = _with_progress(
        "Importing Scholar Labs run",
        lambda report: import_scholar_labs_run(
            _resolve_vault(vault),
            export,
            _resolve_staging(staging),
            dry_run=dry_run,
            commit=commit,
            include_without_pdf=include_without_pdf,
            archive_matched=False,
            archive_export=archive_export,
            upgrade_pdfs=upgrade_pdfs,
            title=resolved_title,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("import-labs")
def import_labs_command(
    vault: VaultArg = None,
    export: OptionalExportArg = None,
    staging: StagingArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    include_without_pdf: IncludeWithoutPdfArg = False,
    auto_enrich: AutoEnrichArg = True,
    upgrade_pdfs: UpgradePdfsArg = True,
    archive_export: ArchiveExportArg = True,
    title: TitleArg = None,
    ui: UiArg = False,
) -> None:
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    resolved_vault = _resolve_vault(vault)
    resolved_staging = _resolve_staging(staging)
    resolved_export = _resolve_latest_export(export, fallback_dir=resolved_staging)
    resolved_title = _resolve_import_title(title, resolved_export, ui=ui)
    summary = _with_progress(
        "Importing Scholar Labs run",
        lambda report: import_scholar_labs_run(
            resolved_vault,
            resolved_export,
            resolved_staging,
            dry_run=dry_run,
            commit=commit,
            include_without_pdf=include_without_pdf,
            archive_matched=True,
            archive_export=archive_export,
            auto_enrich=auto_enrich,
            upgrade_pdfs=upgrade_pdfs,
            title=resolved_title,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("import")
def import_alias_command(
    vault: VaultArg = None,
    export: OptionalExportArg = None,
    staging: StagingArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    include_without_pdf: IncludeWithoutPdfArg = False,
    auto_enrich: AutoEnrichArg = True,
    upgrade_pdfs: UpgradePdfsArg = True,
    archive_export: ArchiveExportArg = True,
    title: TitleArg = None,
    ui: UiArg = False,
) -> None:
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    resolved_vault = _resolve_vault(vault)
    resolved_staging = _resolve_staging(staging)
    resolved_export = _resolve_latest_export(export, fallback_dir=resolved_staging)
    resolved_title = _resolve_import_title(title, resolved_export, ui=ui)
    summary = _with_progress(
        "Importing Scholar Labs run",
        lambda report: import_scholar_labs_run(
            resolved_vault,
            resolved_export,
            resolved_staging,
            dry_run=dry_run,
            commit=commit,
            include_without_pdf=include_without_pdf,
            archive_matched=True,
            archive_export=archive_export,
            auto_enrich=auto_enrich,
            upgrade_pdfs=upgrade_pdfs,
            title=resolved_title,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("import-pdf")
def import_pdf_command(
    vault: VaultArg = None,
    staging: StagingArg = None,
) -> None:
    summary = import_pdf_dropins(_resolve_vault(vault), _resolve_staging(staging), confirm=_confirm)
    console.print(f"Imported {summary['imported']} PDF files.")


@app.command("import-bibtex")
def import_bibtex_command(
    bib: ExportArg,
    vault: VaultArg = None,
) -> None:
    summary = import_bibtex(_resolve_vault(vault), bib)
    console.print(f"Imported {summary['imported']} BibTeX entries.")


@app.command("import-doi")
def import_doi_command(
    doi: str = typer.Option(...),
    vault: VaultArg = None,
) -> None:
    summary = import_doi(_resolve_vault(vault), doi)
    console.print(f"Imported {summary['imported']} DOI stubs.")


@app.command("rebuild")
def rebuild_command(vault: VaultArg = None) -> None:
    resolved_vault = _resolve_vault(vault)
    summary = rebuild_vault(resolved_vault)
    console.print(f"Rebuilt derived files for {resolved_vault}")
    console.print(
        f"- Papers: {summary['papers']} total, "
        f"{summary['paper_cards_written']} card files rewritten, "
        f"{summary['cards_normalized']} normalized."
    )
    console.print(
        f"- Runs: {summary['runs']} run notes refreshed; "
        f"{summary['manifests']} import manifests read."
    )
    if summary["cross_run_links_synced"]:
        console.print(
            f"- Repaired {summary['cross_run_links_synced']} run/card/PDF link(s)."
        )
    console.print(
        f"- Derived outputs: {summary['index_files_written']} indexes, "
        f"{summary['topic_pages_written']} topic pages, "
        f"{summary['llm_files_written']} LLM files, "
        f"{summary['export_files_written']} export files."
    )
    if summary["pdf_filenames_normalized"]:
        console.print(
            f"- Normalized {summary['pdf_filenames_normalized']} attached PDF filename(s)."
        )


@app.command("bibtex")
def bibtex_command(vault: VaultArg = None) -> None:
    output = export_bibtex(_resolve_vault(vault))
    console.print(f"Wrote {output}")


@app.command("doctor")
@app.command("status")
def doctor_command(
    vault: VaultArg = None,
    staging: StagingArg = None,
    json_output: JsonOutputArg = False,
) -> None:
    summary = doctor_vault(
        _resolve_vault(vault),
        staging_path=_optional_staging_path(staging),
    )
    if json_output:
        _print_json(summary)
    else:
        _print_doctor_summary(summary)


@app.command("pdf-doctor")
def pdf_doctor_command(
    vault: VaultArg = None,
    staging: StagingArg = None,
    json_output: JsonOutputArg = False,
) -> None:
    summary = pdf_doctor(
        _resolve_vault(vault),
        staging_path=_optional_staging_path(staging),
    )
    if json_output:
        _print_json(summary)
    else:
        _print_pdf_doctor_summary(summary)


@app.command("notes-missing")
def notes_missing_command(
    vault: VaultArg = None,
    heading: HeadingArg = "PDF reading notes",
    json_output: JsonOutputArg = False,
) -> None:
    summary = notes_missing(_resolve_vault(vault), heading=heading)
    if json_output:
        _print_json(summary)
    else:
        _print_notes_missing(summary)


@app.command("concept-index")
def concept_index_command(
    vault: VaultArg = None,
    json_output: JsonOutputArg = False,
) -> None:
    summary = concept_index(_resolve_vault(vault))
    if json_output:
        _print_json(summary)
    else:
        _print_concept_index(summary)


@app.command("topic-map")
def topic_map_command(
    vault: VaultArg = None,
    mapping: TopicMappingArg = None,
    apply: ApplyArg = False,
    limit: int = typer.Option(30, "--limit", "-n", min=1, help="Topics to show."),
    json_output: JsonOutputArg = False,
) -> None:
    if mapping is None:
        summary = topic_map_report(_resolve_vault(vault), limit=limit)
        if json_output:
            _print_json(summary)
        else:
            _print_topic_report(summary)
        return

    raw_mapping = yaml.safe_load(mapping.read_text(encoding="utf-8")) or {}
    if not isinstance(raw_mapping, dict):
        raise typer.BadParameter("--mapping must contain a YAML mapping.")
    summary = apply_topic_map(_resolve_vault(vault), raw_mapping, apply=apply)
    if json_output:
        _print_json(summary)
    else:
        _print_topic_map_summary(summary)


@app.command("proposal-audit")
def proposal_audit_command(
    proposal: ProposalPathArg,
    vault: VaultArg = None,
    json_output: JsonOutputArg = False,
) -> None:
    summary = proposal_audit(_resolve_vault(vault), proposal)
    if json_output:
        _print_json(summary)
    else:
        _print_proposal_audit(summary)


@proposal_sprint_app.command("scaffold")
def proposal_sprint_scaffold_command(
    slug: ProposalSlugArg,
    vault: VaultArg = None,
    title: ProposalTitleArg = None,
    json_output: JsonOutputArg = False,
) -> None:
    summary = proposal_sprint_scaffold(_resolve_vault(vault), slug, title=title)
    if json_output:
        _print_json(summary)
    else:
        _print_proposal_scaffold(summary)


@app.command("enrich")
def enrich_command(
    vault: VaultArg = None,
    citekey: OptionalCitekeyArg = None,
    only: OnlyArg = "all",
    refresh: RefreshArg = False,
    refresh_abstracts: RefreshAbstractsArg = False,
    retry_failed: RetryFailedArg = False,
    dry_run: DryRunArg = False,
    force: ForceArg = False,
    ui: UiArg = False,
) -> None:
    resolved_vault = _resolve_vault(vault)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Enrichment")
    summary = _with_progress(
        "Enriching vault",
        lambda report: enrich_vault(
            resolved_vault,
            citekey=citekey,
            only=only,
            refresh=refresh,
            refresh_abstracts=refresh_abstracts,
            retry_failed=retry_failed,
            dry_run=dry_run,
            force=force,
            progress=report,
        ),
        gui_progress=progress_ui,
    )
    if progress_ui is not None:
        progress_ui.close()
    _print_enrich_summary(summary)
    shown_in_ui = (
        _show_enrichment_ui(
            summary,
            abstracts=False,
            title="Scholar Vault Enrichment Follow-Up",
        )
        if ui
        else False
    )
    if not shown_in_ui:
        if ui:
            problems = _problem_rows(_detail_rows(summary))
            if problems:
                _print_enrichment_details({"details": problems})
            else:
                console.print("No enrichment follow-up issues found.")
        else:
            _print_enrichment_details(summary)


@app.command("enrich-citations")
def enrich_citations_command(
    vault: VaultArg = None,
    citekey: OptionalCitekeyArg = None,
    only: OnlyArg = "all",
    refresh: RefreshArg = False,
    abstracts: AbstractsArg = False,
    refresh_abstracts: RefreshAbstractsArg = False,
    retry_failed: RetryFailedArg = False,
    dry_run: DryRunArg = False,
    force: ForceArg = False,
    ui: UiArg = False,
) -> None:
    resolved_vault = _resolve_vault(vault)
    enrich_keywords = only == "missing-keywords"
    enrich_abstracts = (
        not enrich_keywords and (abstracts or refresh_abstracts or only == "missing-abstract")
    )
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Enrichment")
    summary = _with_progress(
        "Enriching paper cards",
        lambda report: enrich_citations(
            resolved_vault,
            citekey=citekey,
            only=only,
            refresh=refresh,
            abstracts=abstracts,
            refresh_abstracts=refresh_abstracts,
            retry_failed=retry_failed,
            dry_run=dry_run,
            force=force,
            progress=_enrichment_progress_reporter(
                report,
                abstracts=enrich_abstracts,
                keywords=enrich_keywords,
            ),
        ),
        gui_progress=progress_ui,
    )
    if progress_ui is not None:
        progress_ui.close()
    if enrich_keywords:
        console.print(
            f"Enriched keywords: processed={summary['processed']}, changed={summary['changed']}, "
            f"skipped={summary['skipped']}, resolved={summary['resolved']}, "
            f"unresolved={summary['unresolved']}."
        )
    elif enrich_abstracts:
        console.print(
            f"Enriched abstracts: processed={summary['processed']}, changed={summary['changed']}, "
            f"skipped={summary['skipped']}, resolved={summary['resolved']}, "
            f"verified={summary['verified']}, ambiguous={summary['ambiguous']}, "
            f"unresolved={summary['unresolved']}."
        )
    else:
        console.print(
            f"Enriched citations: processed={summary['processed']}, changed={summary['changed']}, "
            f"skipped={summary['skipped']}, generated={summary['generated']}, "
            f"verified={summary['verified']}, ambiguous={summary['ambiguous']}, "
            f"unresolved={summary['unresolved']}."
        )
    shown_in_ui = (
        _show_enrichment_ui(
            summary,
            abstracts=enrich_abstracts,
            title="Scholar Vault Keyword Results" if enrich_keywords else None,
        )
        if ui
        else False
    )
    if not shown_in_ui:
        if ui:
            problems = _problem_rows(_detail_rows(summary))
            if problems:
                _print_enrichment_details({"details": problems})
            else:
                console.print("No enrichment follow-up issues found.")
        else:
            _print_enrichment_details(summary)
    if ui and not enrich_keywords:
        _print_keyword_followup_hint(resolved_vault, citekey=citekey)


@app.command("reset")
def reset_command(vault: VaultArg = None, yes: YesArg = False) -> None:
    resolved = _resolve_vault(vault)
    if not yes and not _confirm(
        f"Reset vault at {resolved}? This removes imported papers, runs, PDFs, "
        "raw copies inside the vault, derived indexes, and exports."
    ):
        raise typer.Exit(code=1)

    summary = reset_vault(resolved)
    console.print(f"Reset vault at {resolved}. Removed {summary['removed']} vault-managed items.")


@app.command("resume")
def resume_command(
    run: RunIdArg,
    vault: VaultArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    auto_enrich: AutoEnrichArg = True,
    upgrade_pdfs: UpgradePdfsArg = True,
    ui: UiArg = False,
) -> None:
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    summary = _with_progress(
        f"Resuming run {run}",
        lambda report: resume_run(
            _resolve_vault(vault),
            run,
            dry_run=dry_run,
            commit=commit,
            auto_enrich=auto_enrich,
            upgrade_pdfs=upgrade_pdfs,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("rerun")
def rerun_command(
    vault: VaultArg = None,
    run: OptionalRunIdArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    auto_enrich: AutoEnrichArg = True,
    upgrade_pdfs: UpgradePdfsArg = True,
    ui: UiArg = False,
) -> None:
    resolved_vault = _resolve_vault(vault)
    run_id = _select_rerun_run_id(resolved_vault, run, ui=ui)
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    summary = _with_progress(
        f"Rerunning {run_id}",
        lambda report: resume_run(
            resolved_vault,
            run_id,
            dry_run=dry_run,
            commit=commit,
            auto_enrich=auto_enrich,
            upgrade_pdfs=upgrade_pdfs,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("re-run")
def re_run_command(
    vault: VaultArg = None,
    run: OptionalRunIdArg = None,
    dry_run: DryRunArg = False,
    commit: CommitArg = False,
    auto_enrich: AutoEnrichArg = True,
    upgrade_pdfs: UpgradePdfsArg = True,
    ui: UiArg = False,
) -> None:
    resolved_vault = _resolve_vault(vault)
    run_id = _select_rerun_run_id(resolved_vault, run, ui=ui)
    review_match = _match_reviewer(ui) if not dry_run and not commit else None
    confirm = _confirm_callback(ui)
    progress_ui = _make_gui_progress(ui and not dry_run, "Scholar Vault Import")
    summary = _with_progress(
        f"Rerunning {run_id}",
        lambda report: resume_run(
            resolved_vault,
            run_id,
            dry_run=dry_run,
            commit=commit,
            auto_enrich=auto_enrich,
            upgrade_pdfs=upgrade_pdfs,
            confirm=confirm,
            review_match=review_match,
            progress=report,
        ),
        interactive=review_match is not None,
        gui_progress=progress_ui,
    )
    _finish_import_workflow(summary, ui=ui, progress_ui=progress_ui)


@app.command("rename-run")
def rename_run_command(
    run: RunIdArg,
    title: RequiredTitleArg,
    vault: VaultArg = None,
) -> None:
    summary = rename_run(_resolve_vault(vault), run, title)
    console.print(
        f"Renamed run {summary['run']} to {summary['title']}. "
        f"Run note: {summary['new_ref']}."
    )


@app.command("undo")
def undo_command(run: RunIdArg, vault: VaultArg = None) -> None:
    summary = undo_run(_resolve_vault(vault), run)
    console.print(
        f"Undid run {run}. Archived {summary['archived_cards']} cards, "
        f"restored {summary['restored_cards']} cards, archived {summary['archived_pdfs']} PDFs, "
        f"and restored {summary['restored_originals']} staging originals."
    )


@app.command("attach-pdf")
def attach_pdf_command(
    citekey: CitekeyArg,
    pdf: PdfArg,
    vault: VaultArg = None,
) -> None:
    summary = attach_pdf(_resolve_vault(vault), citekey, pdf)
    console.print(
        f"Attached {summary['pdf']} to {citekey} "
        f"(copied={summary['copied']}, verified={summary['verified']})."
    )


@app.command("resolve-citation")
@app.command("set-metadata")
def set_metadata_command(
    citekey: CitekeyArg,
    doi: MetadataDoiArg = None,
    authors: MetadataAuthorsArg = None,
    year: MetadataYearArg = None,
    venue: MetadataVenueArg = None,
    url: MetadataUrlArg = None,
    lock: MetadataLockArg = False,
    vault: VaultArg = None,
) -> None:
    if not any([doi, authors, year, venue, url]):
        raise typer.BadParameter(
            "Provide at least one of --doi, --authors, --year, --venue, or --url."
        )
    summary = set_manual_metadata(
        _resolve_vault(vault),
        citekey,
        doi=doi,
        authors=authors,
        year=year,
        venue=venue,
        url=url,
        lock=lock,
    )
    missing = ", ".join(summary.get("missing_fields") or []) or "none"
    lock_note = ", locked" if summary.get("metadata_lock") else ""
    console.print(
        f"Set manual metadata for {summary['citekey']} "
        f"(metadata={summary['enrichment_status']}, missing={missing}{lock_note}). "
        f"Updated {summary['paper']}."
    )


@app.command("set-abstract")
def set_abstract_command(
    citekey: CitekeyArg,
    text: AbstractTextArg = None,
    abstract_file: AbstractFileArg = None,
    source_url: SourceUrlArg = None,
    lock: AbstractLockArg = True,
    vault: VaultArg = None,
) -> None:
    if text and abstract_file:
        raise typer.BadParameter("Use either --text or --file, not both.")
    if abstract_file:
        abstract = abstract_file.read_text(encoding="utf-8")
    elif text:
        abstract = text
    else:
        raise typer.BadParameter("Provide a manual abstract with --text or --file.")

    summary = set_manual_abstract(
        _resolve_vault(vault),
        citekey,
        abstract,
        source_url=source_url,
        lock=lock,
    )
    lock_note = "locked" if summary["locked"] else "unlocked"
    console.print(
        f"Set manual abstract for {summary['citekey']} ({lock_note}). "
        f"Updated {summary['paper']}."
    )


@app.command("set-keywords")
def set_keywords_command(
    citekey: CitekeyArg,
    text: KeywordTextArg = None,
    keyword_file: KeywordFileArg = None,
    replace: KeywordReplaceArg = False,
    none: KeywordNoneArg = False,
    vault: VaultArg = None,
) -> None:
    if none and (text or keyword_file):
        raise typer.BadParameter("Use --none without --text or --file.")
    if none:
        summary = confirm_no_publication_keywords(_resolve_vault(vault), citekey)
        console.print(
            f"Confirmed no publication keywords for {summary['citekey']}. "
            f"Updated {summary['paper']}."
        )
        return
    if text and keyword_file:
        raise typer.BadParameter("Use either --text or --file, not both.")
    if keyword_file:
        keywords = keyword_file.read_text(encoding="utf-8")
    elif text:
        keywords = text
    else:
        raise typer.BadParameter("Provide manual keywords with --text or --file.")

    summary = set_manual_keywords(
        _resolve_vault(vault),
        citekey,
        keywords,
        replace=replace,
    )
    console.print(
        f"Set {summary['count']} keywords for {summary['citekey']}. "
        f"Updated {summary['paper']}."
    )


@app.command("unmatched")
def unmatched_command(vault: VaultArg = None) -> None:
    rows = list_unmatched(_resolve_vault(vault))
    if not rows:
        console.print("No unmatched PDFs.")
        return
    for row in rows:
        console.print(
            f"{row['run_id']}: {row['original_path']} "
            f"(decision={row['decision']}, score={row['score']}, proposed={row['proposed_match']})"
        )


@app.command("match-staging")
@app.command("staging-matches")
def match_staging_command(
    vault: VaultArg = None,
    staging: StagingArg = None,
    title: MatchTitleArg = None,
    pdf: OptionalPdfArg = None,
    min_score: int = typer.Option(
        60,
        "--min-score",
        min=0,
        max=100,
        help="Only show run results at or above this score.",
    ),
    limit: int = typer.Option(
        50,
        "--limit",
        "-n",
        min=0,
        help="Maximum candidate rows to show; 0 shows all.",
    ),
    unselected_only: bool = typer.Option(
        False,
        "--unselected-only",
        help="Hide run results that are already selected and have an attached PDF.",
    ),
    ui: UiArg = False,
) -> None:
    resolved_vault = _resolve_vault(vault)
    resolved_staging = _resolve_staging(staging)
    if ui:
        run_id = _choose_staging_match_run_id(
            resolved_vault,
            resolved_staging,
            title=title,
            pdf=pdf,
            min_score=min_score,
            limit=limit,
            unselected_only=unselected_only,
            run_callback=lambda selected_run: _rerun_selected_match(
                resolved_vault,
                selected_run,
            ),
        )
        if run_id:
            _rerun_selected_match(resolved_vault, run_id)
        return

    summary = _with_progress(
        "Matching staged PDFs against previous runs",
        lambda report: find_staged_run_matches(
            resolved_vault,
            resolved_staging,
            title=title,
            pdf_path=pdf,
            min_score=min_score,
            limit=limit,
            unselected_only=unselected_only,
            progress=report,
        ),
    )
    _print_staged_match_table(summary)


@app.command("clean-staging")
def clean_staging_command(vault: VaultArg = None, staging: StagingArg = None) -> None:
    summary = clean_staging(_resolve_vault(vault), _resolve_staging(staging))
    console.print(
        f"Cleaned staging. Moved {summary['moved']} files into vault archive "
        f"and kept {summary['kept']} files."
    )


@app.command("cleanup-run")
def cleanup_run_command(
    run: RunIdArg,
    vault: VaultArg = None,
    selected_only: SelectedOnlyArg = False,
) -> None:
    if not selected_only:
        raise typer.BadParameter("Only --selected-only is currently supported.")
    summary = cleanup_run_selected_only(_resolve_vault(vault), run)
    console.print(
        f"Cleaned run {run}. Archived {summary['archived']} candidate-only cards "
        f"and kept {summary['kept']} cards."
    )


def main() -> None:
    app()
